version: '3'

services:
  app:
    image: apiad/matcom-dashboard:latest
    build: .
    environment:
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - SECRET=${SECRET}
    user: ${USER}
    ports:
      - "8501:8501"
    volumes:
      - "./:/src"
    working_dir: "/src"
    command: [ "streamlit", "run", "/src/app/🏠_inicio.py" ]

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app


volumes:
  caddy_config:
  caddy_data:
